
version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: kirorus/api_yamdb:latest
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  db_volume: